name: Build an Test Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images for python
        run: docker build -t my-app:1.0.0 -f ./api/Dockerfile ./api

      - name: Build images for mongo
        run: docker build -t my-mongo:1.0.0 -f ./mongo/Dockerfile ./mongo

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Scout Scan API
        uses: docker/scout-action@v1
        with:
          command: cves
          image: my-app:1.0.0
          file: ./api/Dockerfile
          only-severities: critical,high
          exit-code: false

      - name: Docker Scout Scan Mongo
        uses: docker/scout-action@v1
        with:
          command: cves
          image: my-mongo:1.0.0
          file: ./mongo/Dockerfile
          only-severities: critical,high
          exit-code: false
      
  deploy_test:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the stack
        run: docker compose up -d

      - name: Show running containers
        run: docker ps
